# Generated by Django 2.1 on 2021-04-04 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('qualification', models.CharField(max_length=50)),
                ('mail_id', models.CharField(max_length=50)),
                ('duration', models.IntegerField(null=True)),
                ('joining_date', models.DateField(null=True)),
                ('paid_amount', models.IntegerField(null=True)),
                ('balance_amount', models.IntegerField(null=True)),
            ],
        ),
    ]
