# Generated by Django 2.1 on 2021-04-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_appe', '0002_course_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='ph',
            field=models.ForeignKey(null=True, on_delete=False, to='orm_appe.STUDENT'),
        ),
    ]
