# Generated by Django 2.1 on 2021-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_appe', '0003_phone_ph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='ph_number',
            field=models.BigIntegerField(max_length=30),
        ),
    ]
