# Generated by Django 2.1 on 2021-04-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_appe', '0005_auto_20210410_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.ManyToManyField(to='orm_appe.STUDENT'),
        ),
    ]
